/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedCheckoutRouteImport } from './routes/_authenticated/checkout'
import { Route as AuthenticatedCommunicationRouteImport } from './routes/_authenticated/communication'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedJathagamRouteImport } from './routes/_authenticated/jathagam'
import { Route as AuthenticatedMatchesRouteImport } from './routes/_authenticated/matches'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedOfficeMessagesRouteImport } from './routes/_authenticated/office-messages'
import { Route as AuthenticatedRegisterRouteImport } from './routes/_authenticated/register'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as TaIndexRouteImport } from './routes/ta/index'
import { Route as TaPrivacyRouteImport } from './routes/ta/privacy'
import { Route as TaRefundPolicyRouteImport } from './routes/ta/refund-policy'
import { Route as TaTermsRouteImport } from './routes/ta/terms'
import { Route as AuthenticatedTaCommunicationRouteImport } from './routes/_authenticated/ta.communication'
import { Route as AuthenticatedTaDashboardRouteImport } from './routes/_authenticated/ta.dashboard'
import { Route as AuthenticatedTaJathagamRouteImport } from './routes/_authenticated/ta.jathagam'
import { Route as AuthenticatedTaOfficeMessagesRouteImport } from './routes/_authenticated/ta.office-messages'
import { Route as AuthenticatedTaRegisterRouteImport } from './routes/_authenticated/ta.register'
import { Route as AuthenticatedTaSupportRouteImport } from './routes/_authenticated/ta.support'
import { Route as AuthenticatedEnAdminIndexRouteImport } from './routes/_authenticated/en.admin.index'
import { Route as AuthenticatedEnAdminAlertsRouteImport } from './routes/_authenticated/en.admin.alerts'
import { Route as AuthenticatedEnAdminApprovalsRouteImport } from './routes/_authenticated/en.admin.approvals'
import { Route as AuthenticatedEnAdminCommunicationRouteImport } from './routes/_authenticated/en.admin.communication'
import { Route as AuthenticatedEnAdminJathagamRouteImport } from './routes/_authenticated/en.admin.jathagam'
import { Route as AuthenticatedEnAdminMembersRouteImport } from './routes/_authenticated/en.admin.members'
import { Route as AuthenticatedEnAdminMessagesRouteImport } from './routes/_authenticated/en.admin.messages'
import { Route as AuthenticatedEnAdminPaymentsRouteImport } from './routes/_authenticated/en.admin.payments'
import { Route as AuthenticatedEnAdminReportsRouteImport } from './routes/_authenticated/en.admin.reports'
import { Route as AuthenticatedEnAdminSettingsRouteImport } from './routes/_authenticated/en.admin.settings'
import { Route as AuthenticatedEnAdminSupportRouteImport } from './routes/_authenticated/en.admin.support'
import { Route as AuthenticatedTnAdminIndexRouteImport } from './routes/_authenticated/tn.admin.index'
import { Route as AuthenticatedTnAdminAlertsRouteImport } from './routes/_authenticated/tn.admin.alerts'
import { Route as AuthenticatedTnAdminApprovalsRouteImport } from './routes/_authenticated/tn.admin.approvals'
import { Route as AuthenticatedTnAdminCommunicationRouteImport } from './routes/_authenticated/tn.admin.communication'
import { Route as AuthenticatedTnAdminJathagamRouteImport } from './routes/_authenticated/tn.admin.jathagam'
import { Route as AuthenticatedTnAdminMembersRouteImport } from './routes/_authenticated/tn.admin.members'
import { Route as AuthenticatedTnAdminMessagesRouteImport } from './routes/_authenticated/tn.admin.messages'
import { Route as AuthenticatedTnAdminPaymentsRouteImport } from './routes/_authenticated/tn.admin.payments'
import { Route as AuthenticatedTnAdminReportsRouteImport } from './routes/_authenticated/tn.admin.reports'
import { Route as AuthenticatedTnAdminSettingsRouteImport } from './routes/_authenticated/tn.admin.settings'
import { Route as AuthenticatedTnAdminSupportRouteImport } from './routes/_authenticated/tn.admin.support'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCheckoutRoute = AuthenticatedCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommunicationRoute =
  AuthenticatedCommunicationRouteImport.update({
    id: '/communication',
    path: '/communication',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJathagamRoute = AuthenticatedJathagamRouteImport.update({
  id: '/jathagam',
  path: '/jathagam',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMatchesRoute = AuthenticatedMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOfficeMessagesRoute =
  AuthenticatedOfficeMessagesRouteImport.update({
    id: '/office-messages',
    path: '/office-messages',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRegisterRoute = AuthenticatedRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const TaIndexRoute = TaIndexRouteImport.update({
  id: '/ta/',
  path: '/ta/',
  getParentRoute: () => rootRouteImport,
} as any)
const TaPrivacyRoute = TaPrivacyRouteImport.update({
  id: '/ta/privacy',
  path: '/ta/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TaRefundPolicyRoute = TaRefundPolicyRouteImport.update({
  id: '/ta/refund-policy',
  path: '/ta/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const TaTermsRoute = TaTermsRouteImport.update({
  id: '/ta/terms',
  path: '/ta/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTaCommunicationRoute =
  AuthenticatedTaCommunicationRouteImport.update({
    id: '/ta/communication',
    path: '/ta/communication',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTaDashboardRoute =
  AuthenticatedTaDashboardRouteImport.update({
    id: '/ta/dashboard',
    path: '/ta/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTaJathagamRoute = AuthenticatedTaJathagamRouteImport.update({
  id: '/ta/jathagam',
  path: '/ta/jathagam',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTaOfficeMessagesRoute =
  AuthenticatedTaOfficeMessagesRouteImport.update({
    id: '/ta/office-messages',
    path: '/ta/office-messages',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTaRegisterRoute = AuthenticatedTaRegisterRouteImport.update({
  id: '/ta/register',
  path: '/ta/register',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTaSupportRoute = AuthenticatedTaSupportRouteImport.update({
  id: '/ta/support',
  path: '/ta/support',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEnAdminIndexRoute =
  AuthenticatedEnAdminIndexRouteImport.update({
    id: '/en/admin/',
    path: '/en/admin/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEnAdminAlertsRoute =
  AuthenticatedEnAdminAlertsRouteImport.update({
    id: '/en/admin/alerts',
    path: '/en/admin/alerts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEnAdminApprovalsRoute =
  AuthenticatedEnAdminApprovalsRouteImport.update({
    id: '/en/admin/approvals',
    path: '/en/admin/approvals',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEnAdminCommunicationRoute =
  AuthenticatedEnAdminCommunicationRouteImport.update({
    id: '/en/admin/communication',
    path: '/en/admin/communication',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEnAdminJathagamRoute =
  AuthenticatedEnAdminJathagamRouteImport.update({
    id: '/en/admin/jathagam',
    path: '/en/admin/jathagam',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEnAdminMembersRoute =
  AuthenticatedEnAdminMembersRouteImport.update({
    id: '/en/admin/members',
    path: '/en/admin/members',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEnAdminMessagesRoute =
  AuthenticatedEnAdminMessagesRouteImport.update({
    id: '/en/admin/messages',
    path: '/en/admin/messages',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEnAdminPaymentsRoute =
  AuthenticatedEnAdminPaymentsRouteImport.update({
    id: '/en/admin/payments',
    path: '/en/admin/payments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEnAdminReportsRoute =
  AuthenticatedEnAdminReportsRouteImport.update({
    id: '/en/admin/reports',
    path: '/en/admin/reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEnAdminSettingsRoute =
  AuthenticatedEnAdminSettingsRouteImport.update({
    id: '/en/admin/settings',
    path: '/en/admin/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEnAdminSupportRoute =
  AuthenticatedEnAdminSupportRouteImport.update({
    id: '/en/admin/support',
    path: '/en/admin/support',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTnAdminIndexRoute =
  AuthenticatedTnAdminIndexRouteImport.update({
    id: '/tn/admin/',
    path: '/tn/admin/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTnAdminAlertsRoute =
  AuthenticatedTnAdminAlertsRouteImport.update({
    id: '/tn/admin/alerts',
    path: '/tn/admin/alerts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTnAdminApprovalsRoute =
  AuthenticatedTnAdminApprovalsRouteImport.update({
    id: '/tn/admin/approvals',
    path: '/tn/admin/approvals',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTnAdminCommunicationRoute =
  AuthenticatedTnAdminCommunicationRouteImport.update({
    id: '/tn/admin/communication',
    path: '/tn/admin/communication',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTnAdminJathagamRoute =
  AuthenticatedTnAdminJathagamRouteImport.update({
    id: '/tn/admin/jathagam',
    path: '/tn/admin/jathagam',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTnAdminMembersRoute =
  AuthenticatedTnAdminMembersRouteImport.update({
    id: '/tn/admin/members',
    path: '/tn/admin/members',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTnAdminMessagesRoute =
  AuthenticatedTnAdminMessagesRouteImport.update({
    id: '/tn/admin/messages',
    path: '/tn/admin/messages',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTnAdminPaymentsRoute =
  AuthenticatedTnAdminPaymentsRouteImport.update({
    id: '/tn/admin/payments',
    path: '/tn/admin/payments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTnAdminReportsRoute =
  AuthenticatedTnAdminReportsRouteImport.update({
    id: '/tn/admin/reports',
    path: '/tn/admin/reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTnAdminSettingsRoute =
  AuthenticatedTnAdminSettingsRouteImport.update({
    id: '/tn/admin/settings',
    path: '/tn/admin/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTnAdminSupportRoute =
  AuthenticatedTnAdminSupportRouteImport.update({
    id: '/tn/admin/support',
    path: '/tn/admin/support',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/communication': typeof AuthenticatedCommunicationRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/jathagam': typeof AuthenticatedJathagamRoute
  '/matches': typeof AuthenticatedMatchesRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/office-messages': typeof AuthenticatedOfficeMessagesRoute
  '/register': typeof AuthenticatedRegisterRoute
  '/support': typeof AuthenticatedSupportRoute
  '/ta/privacy': typeof TaPrivacyRoute
  '/ta/refund-policy': typeof TaRefundPolicyRoute
  '/ta/terms': typeof TaTermsRoute
  '/ta/': typeof TaIndexRoute
  '/ta/communication': typeof AuthenticatedTaCommunicationRoute
  '/ta/dashboard': typeof AuthenticatedTaDashboardRoute
  '/ta/jathagam': typeof AuthenticatedTaJathagamRoute
  '/ta/office-messages': typeof AuthenticatedTaOfficeMessagesRoute
  '/ta/register': typeof AuthenticatedTaRegisterRoute
  '/ta/support': typeof AuthenticatedTaSupportRoute
  '/en/admin/alerts': typeof AuthenticatedEnAdminAlertsRoute
  '/en/admin/approvals': typeof AuthenticatedEnAdminApprovalsRoute
  '/en/admin/communication': typeof AuthenticatedEnAdminCommunicationRoute
  '/en/admin/jathagam': typeof AuthenticatedEnAdminJathagamRoute
  '/en/admin/members': typeof AuthenticatedEnAdminMembersRoute
  '/en/admin/messages': typeof AuthenticatedEnAdminMessagesRoute
  '/en/admin/payments': typeof AuthenticatedEnAdminPaymentsRoute
  '/en/admin/reports': typeof AuthenticatedEnAdminReportsRoute
  '/en/admin/settings': typeof AuthenticatedEnAdminSettingsRoute
  '/en/admin/support': typeof AuthenticatedEnAdminSupportRoute
  '/tn/admin/alerts': typeof AuthenticatedTnAdminAlertsRoute
  '/tn/admin/approvals': typeof AuthenticatedTnAdminApprovalsRoute
  '/tn/admin/communication': typeof AuthenticatedTnAdminCommunicationRoute
  '/tn/admin/jathagam': typeof AuthenticatedTnAdminJathagamRoute
  '/tn/admin/members': typeof AuthenticatedTnAdminMembersRoute
  '/tn/admin/messages': typeof AuthenticatedTnAdminMessagesRoute
  '/tn/admin/payments': typeof AuthenticatedTnAdminPaymentsRoute
  '/tn/admin/reports': typeof AuthenticatedTnAdminReportsRoute
  '/tn/admin/settings': typeof AuthenticatedTnAdminSettingsRoute
  '/tn/admin/support': typeof AuthenticatedTnAdminSupportRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/en/admin/': typeof AuthenticatedEnAdminIndexRoute
  '/tn/admin/': typeof AuthenticatedTnAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/communication': typeof AuthenticatedCommunicationRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/jathagam': typeof AuthenticatedJathagamRoute
  '/matches': typeof AuthenticatedMatchesRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/office-messages': typeof AuthenticatedOfficeMessagesRoute
  '/register': typeof AuthenticatedRegisterRoute
  '/support': typeof AuthenticatedSupportRoute
  '/ta/privacy': typeof TaPrivacyRoute
  '/ta/refund-policy': typeof TaRefundPolicyRoute
  '/ta/terms': typeof TaTermsRoute
  '/ta': typeof TaIndexRoute
  '/ta/communication': typeof AuthenticatedTaCommunicationRoute
  '/ta/dashboard': typeof AuthenticatedTaDashboardRoute
  '/ta/jathagam': typeof AuthenticatedTaJathagamRoute
  '/ta/office-messages': typeof AuthenticatedTaOfficeMessagesRoute
  '/ta/register': typeof AuthenticatedTaRegisterRoute
  '/ta/support': typeof AuthenticatedTaSupportRoute
  '/en/admin/alerts': typeof AuthenticatedEnAdminAlertsRoute
  '/en/admin/approvals': typeof AuthenticatedEnAdminApprovalsRoute
  '/en/admin/communication': typeof AuthenticatedEnAdminCommunicationRoute
  '/en/admin/jathagam': typeof AuthenticatedEnAdminJathagamRoute
  '/en/admin/members': typeof AuthenticatedEnAdminMembersRoute
  '/en/admin/messages': typeof AuthenticatedEnAdminMessagesRoute
  '/en/admin/payments': typeof AuthenticatedEnAdminPaymentsRoute
  '/en/admin/reports': typeof AuthenticatedEnAdminReportsRoute
  '/en/admin/settings': typeof AuthenticatedEnAdminSettingsRoute
  '/en/admin/support': typeof AuthenticatedEnAdminSupportRoute
  '/tn/admin/alerts': typeof AuthenticatedTnAdminAlertsRoute
  '/tn/admin/approvals': typeof AuthenticatedTnAdminApprovalsRoute
  '/tn/admin/communication': typeof AuthenticatedTnAdminCommunicationRoute
  '/tn/admin/jathagam': typeof AuthenticatedTnAdminJathagamRoute
  '/tn/admin/members': typeof AuthenticatedTnAdminMembersRoute
  '/tn/admin/messages': typeof AuthenticatedTnAdminMessagesRoute
  '/tn/admin/payments': typeof AuthenticatedTnAdminPaymentsRoute
  '/tn/admin/reports': typeof AuthenticatedTnAdminReportsRoute
  '/tn/admin/settings': typeof AuthenticatedTnAdminSettingsRoute
  '/tn/admin/support': typeof AuthenticatedTnAdminSupportRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/en/admin': typeof AuthenticatedEnAdminIndexRoute
  '/tn/admin': typeof AuthenticatedTnAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/checkout': typeof AuthenticatedCheckoutRoute
  '/_authenticated/communication': typeof AuthenticatedCommunicationRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/jathagam': typeof AuthenticatedJathagamRoute
  '/_authenticated/matches': typeof AuthenticatedMatchesRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/office-messages': typeof AuthenticatedOfficeMessagesRoute
  '/_authenticated/register': typeof AuthenticatedRegisterRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/ta/privacy': typeof TaPrivacyRoute
  '/ta/refund-policy': typeof TaRefundPolicyRoute
  '/ta/terms': typeof TaTermsRoute
  '/ta/': typeof TaIndexRoute
  '/_authenticated/ta/communication': typeof AuthenticatedTaCommunicationRoute
  '/_authenticated/ta/dashboard': typeof AuthenticatedTaDashboardRoute
  '/_authenticated/ta/jathagam': typeof AuthenticatedTaJathagamRoute
  '/_authenticated/ta/office-messages': typeof AuthenticatedTaOfficeMessagesRoute
  '/_authenticated/ta/register': typeof AuthenticatedTaRegisterRoute
  '/_authenticated/ta/support': typeof AuthenticatedTaSupportRoute
  '/_authenticated/en/admin/alerts': typeof AuthenticatedEnAdminAlertsRoute
  '/_authenticated/en/admin/approvals': typeof AuthenticatedEnAdminApprovalsRoute
  '/_authenticated/en/admin/communication': typeof AuthenticatedEnAdminCommunicationRoute
  '/_authenticated/en/admin/jathagam': typeof AuthenticatedEnAdminJathagamRoute
  '/_authenticated/en/admin/members': typeof AuthenticatedEnAdminMembersRoute
  '/_authenticated/en/admin/messages': typeof AuthenticatedEnAdminMessagesRoute
  '/_authenticated/en/admin/payments': typeof AuthenticatedEnAdminPaymentsRoute
  '/_authenticated/en/admin/reports': typeof AuthenticatedEnAdminReportsRoute
  '/_authenticated/en/admin/settings': typeof AuthenticatedEnAdminSettingsRoute
  '/_authenticated/en/admin/support': typeof AuthenticatedEnAdminSupportRoute
  '/_authenticated/tn/admin/alerts': typeof AuthenticatedTnAdminAlertsRoute
  '/_authenticated/tn/admin/approvals': typeof AuthenticatedTnAdminApprovalsRoute
  '/_authenticated/tn/admin/communication': typeof AuthenticatedTnAdminCommunicationRoute
  '/_authenticated/tn/admin/jathagam': typeof AuthenticatedTnAdminJathagamRoute
  '/_authenticated/tn/admin/members': typeof AuthenticatedTnAdminMembersRoute
  '/_authenticated/tn/admin/messages': typeof AuthenticatedTnAdminMessagesRoute
  '/_authenticated/tn/admin/payments': typeof AuthenticatedTnAdminPaymentsRoute
  '/_authenticated/tn/admin/reports': typeof AuthenticatedTnAdminReportsRoute
  '/_authenticated/tn/admin/settings': typeof AuthenticatedTnAdminSettingsRoute
  '/_authenticated/tn/admin/support': typeof AuthenticatedTnAdminSupportRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/_authenticated/en/admin/': typeof AuthenticatedEnAdminIndexRoute
  '/_authenticated/tn/admin/': typeof AuthenticatedTnAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/privacy'
    | '/refund-policy'
    | '/reset-password'
    | '/terms'
    | '/admin'
    | '/checkout'
    | '/communication'
    | '/dashboard'
    | '/jathagam'
    | '/matches'
    | '/messages'
    | '/office-messages'
    | '/register'
    | '/support'
    | '/ta/privacy'
    | '/ta/refund-policy'
    | '/ta/terms'
    | '/ta/'
    | '/ta/communication'
    | '/ta/dashboard'
    | '/ta/jathagam'
    | '/ta/office-messages'
    | '/ta/register'
    | '/ta/support'
    | '/en/admin/alerts'
    | '/en/admin/approvals'
    | '/en/admin/communication'
    | '/en/admin/jathagam'
    | '/en/admin/members'
    | '/en/admin/messages'
    | '/en/admin/payments'
    | '/en/admin/reports'
    | '/en/admin/settings'
    | '/en/admin/support'
    | '/tn/admin/alerts'
    | '/tn/admin/approvals'
    | '/tn/admin/communication'
    | '/tn/admin/jathagam'
    | '/tn/admin/members'
    | '/tn/admin/messages'
    | '/tn/admin/payments'
    | '/tn/admin/reports'
    | '/tn/admin/settings'
    | '/tn/admin/support'
    | '/lovable/email/transactional/preview'
    | '/en/admin/'
    | '/tn/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/privacy'
    | '/refund-policy'
    | '/reset-password'
    | '/terms'
    | '/admin'
    | '/checkout'
    | '/communication'
    | '/dashboard'
    | '/jathagam'
    | '/matches'
    | '/messages'
    | '/office-messages'
    | '/register'
    | '/support'
    | '/ta/privacy'
    | '/ta/refund-policy'
    | '/ta/terms'
    | '/ta'
    | '/ta/communication'
    | '/ta/dashboard'
    | '/ta/jathagam'
    | '/ta/office-messages'
    | '/ta/register'
    | '/ta/support'
    | '/en/admin/alerts'
    | '/en/admin/approvals'
    | '/en/admin/communication'
    | '/en/admin/jathagam'
    | '/en/admin/members'
    | '/en/admin/messages'
    | '/en/admin/payments'
    | '/en/admin/reports'
    | '/en/admin/settings'
    | '/en/admin/support'
    | '/tn/admin/alerts'
    | '/tn/admin/approvals'
    | '/tn/admin/communication'
    | '/tn/admin/jathagam'
    | '/tn/admin/members'
    | '/tn/admin/messages'
    | '/tn/admin/payments'
    | '/tn/admin/reports'
    | '/tn/admin/settings'
    | '/tn/admin/support'
    | '/lovable/email/transactional/preview'
    | '/en/admin'
    | '/tn/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/privacy'
    | '/refund-policy'
    | '/reset-password'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/checkout'
    | '/_authenticated/communication'
    | '/_authenticated/dashboard'
    | '/_authenticated/jathagam'
    | '/_authenticated/matches'
    | '/_authenticated/messages'
    | '/_authenticated/office-messages'
    | '/_authenticated/register'
    | '/_authenticated/support'
    | '/ta/privacy'
    | '/ta/refund-policy'
    | '/ta/terms'
    | '/ta/'
    | '/_authenticated/ta/communication'
    | '/_authenticated/ta/dashboard'
    | '/_authenticated/ta/jathagam'
    | '/_authenticated/ta/office-messages'
    | '/_authenticated/ta/register'
    | '/_authenticated/ta/support'
    | '/_authenticated/en/admin/alerts'
    | '/_authenticated/en/admin/approvals'
    | '/_authenticated/en/admin/communication'
    | '/_authenticated/en/admin/jathagam'
    | '/_authenticated/en/admin/members'
    | '/_authenticated/en/admin/messages'
    | '/_authenticated/en/admin/payments'
    | '/_authenticated/en/admin/reports'
    | '/_authenticated/en/admin/settings'
    | '/_authenticated/en/admin/support'
    | '/_authenticated/tn/admin/alerts'
    | '/_authenticated/tn/admin/approvals'
    | '/_authenticated/tn/admin/communication'
    | '/_authenticated/tn/admin/jathagam'
    | '/_authenticated/tn/admin/members'
    | '/_authenticated/tn/admin/messages'
    | '/_authenticated/tn/admin/payments'
    | '/_authenticated/tn/admin/reports'
    | '/_authenticated/tn/admin/settings'
    | '/_authenticated/tn/admin/support'
    | '/lovable/email/transactional/preview'
    | '/_authenticated/en/admin/'
    | '/_authenticated/tn/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  TaPrivacyRoute: typeof TaPrivacyRoute
  TaRefundPolicyRoute: typeof TaRefundPolicyRoute
  TaTermsRoute: typeof TaTermsRoute
  TaIndexRoute: typeof TaIndexRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checkout': {
      id: '/_authenticated/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AuthenticatedCheckoutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/communication': {
      id: '/_authenticated/communication'
      path: '/communication'
      fullPath: '/communication'
      preLoaderRoute: typeof AuthenticatedCommunicationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jathagam': {
      id: '/_authenticated/jathagam'
      path: '/jathagam'
      fullPath: '/jathagam'
      preLoaderRoute: typeof AuthenticatedJathagamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/matches': {
      id: '/_authenticated/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof AuthenticatedMatchesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/office-messages': {
      id: '/_authenticated/office-messages'
      path: '/office-messages'
      fullPath: '/office-messages'
      preLoaderRoute: typeof AuthenticatedOfficeMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/register': {
      id: '/_authenticated/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthenticatedRegisterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/ta/': {
      id: '/ta/'
      path: '/ta'
      fullPath: '/ta/'
      preLoaderRoute: typeof TaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ta/privacy': {
      id: '/ta/privacy'
      path: '/ta/privacy'
      fullPath: '/ta/privacy'
      preLoaderRoute: typeof TaPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ta/refund-policy': {
      id: '/ta/refund-policy'
      path: '/ta/refund-policy'
      fullPath: '/ta/refund-policy'
      preLoaderRoute: typeof TaRefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ta/terms': {
      id: '/ta/terms'
      path: '/ta/terms'
      fullPath: '/ta/terms'
      preLoaderRoute: typeof TaTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ta/communication': {
      id: '/_authenticated/ta/communication'
      path: '/ta/communication'
      fullPath: '/ta/communication'
      preLoaderRoute: typeof AuthenticatedTaCommunicationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ta/dashboard': {
      id: '/_authenticated/ta/dashboard'
      path: '/ta/dashboard'
      fullPath: '/ta/dashboard'
      preLoaderRoute: typeof AuthenticatedTaDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ta/jathagam': {
      id: '/_authenticated/ta/jathagam'
      path: '/ta/jathagam'
      fullPath: '/ta/jathagam'
      preLoaderRoute: typeof AuthenticatedTaJathagamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ta/office-messages': {
      id: '/_authenticated/ta/office-messages'
      path: '/ta/office-messages'
      fullPath: '/ta/office-messages'
      preLoaderRoute: typeof AuthenticatedTaOfficeMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ta/register': {
      id: '/_authenticated/ta/register'
      path: '/ta/register'
      fullPath: '/ta/register'
      preLoaderRoute: typeof AuthenticatedTaRegisterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ta/support': {
      id: '/_authenticated/ta/support'
      path: '/ta/support'
      fullPath: '/ta/support'
      preLoaderRoute: typeof AuthenticatedTaSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/en/admin/': {
      id: '/_authenticated/en/admin/'
      path: '/en/admin'
      fullPath: '/en/admin/'
      preLoaderRoute: typeof AuthenticatedEnAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/en/admin/alerts': {
      id: '/_authenticated/en/admin/alerts'
      path: '/en/admin/alerts'
      fullPath: '/en/admin/alerts'
      preLoaderRoute: typeof AuthenticatedEnAdminAlertsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/en/admin/approvals': {
      id: '/_authenticated/en/admin/approvals'
      path: '/en/admin/approvals'
      fullPath: '/en/admin/approvals'
      preLoaderRoute: typeof AuthenticatedEnAdminApprovalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/en/admin/communication': {
      id: '/_authenticated/en/admin/communication'
      path: '/en/admin/communication'
      fullPath: '/en/admin/communication'
      preLoaderRoute: typeof AuthenticatedEnAdminCommunicationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/en/admin/jathagam': {
      id: '/_authenticated/en/admin/jathagam'
      path: '/en/admin/jathagam'
      fullPath: '/en/admin/jathagam'
      preLoaderRoute: typeof AuthenticatedEnAdminJathagamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/en/admin/members': {
      id: '/_authenticated/en/admin/members'
      path: '/en/admin/members'
      fullPath: '/en/admin/members'
      preLoaderRoute: typeof AuthenticatedEnAdminMembersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/en/admin/messages': {
      id: '/_authenticated/en/admin/messages'
      path: '/en/admin/messages'
      fullPath: '/en/admin/messages'
      preLoaderRoute: typeof AuthenticatedEnAdminMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/en/admin/payments': {
      id: '/_authenticated/en/admin/payments'
      path: '/en/admin/payments'
      fullPath: '/en/admin/payments'
      preLoaderRoute: typeof AuthenticatedEnAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/en/admin/reports': {
      id: '/_authenticated/en/admin/reports'
      path: '/en/admin/reports'
      fullPath: '/en/admin/reports'
      preLoaderRoute: typeof AuthenticatedEnAdminReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/en/admin/settings': {
      id: '/_authenticated/en/admin/settings'
      path: '/en/admin/settings'
      fullPath: '/en/admin/settings'
      preLoaderRoute: typeof AuthenticatedEnAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/en/admin/support': {
      id: '/_authenticated/en/admin/support'
      path: '/en/admin/support'
      fullPath: '/en/admin/support'
      preLoaderRoute: typeof AuthenticatedEnAdminSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tn/admin/': {
      id: '/_authenticated/tn/admin/'
      path: '/tn/admin'
      fullPath: '/tn/admin/'
      preLoaderRoute: typeof AuthenticatedTnAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tn/admin/alerts': {
      id: '/_authenticated/tn/admin/alerts'
      path: '/tn/admin/alerts'
      fullPath: '/tn/admin/alerts'
      preLoaderRoute: typeof AuthenticatedTnAdminAlertsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tn/admin/approvals': {
      id: '/_authenticated/tn/admin/approvals'
      path: '/tn/admin/approvals'
      fullPath: '/tn/admin/approvals'
      preLoaderRoute: typeof AuthenticatedTnAdminApprovalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tn/admin/communication': {
      id: '/_authenticated/tn/admin/communication'
      path: '/tn/admin/communication'
      fullPath: '/tn/admin/communication'
      preLoaderRoute: typeof AuthenticatedTnAdminCommunicationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tn/admin/jathagam': {
      id: '/_authenticated/tn/admin/jathagam'
      path: '/tn/admin/jathagam'
      fullPath: '/tn/admin/jathagam'
      preLoaderRoute: typeof AuthenticatedTnAdminJathagamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tn/admin/members': {
      id: '/_authenticated/tn/admin/members'
      path: '/tn/admin/members'
      fullPath: '/tn/admin/members'
      preLoaderRoute: typeof AuthenticatedTnAdminMembersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tn/admin/messages': {
      id: '/_authenticated/tn/admin/messages'
      path: '/tn/admin/messages'
      fullPath: '/tn/admin/messages'
      preLoaderRoute: typeof AuthenticatedTnAdminMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tn/admin/payments': {
      id: '/_authenticated/tn/admin/payments'
      path: '/tn/admin/payments'
      fullPath: '/tn/admin/payments'
      preLoaderRoute: typeof AuthenticatedTnAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tn/admin/reports': {
      id: '/_authenticated/tn/admin/reports'
      path: '/tn/admin/reports'
      fullPath: '/tn/admin/reports'
      preLoaderRoute: typeof AuthenticatedTnAdminReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tn/admin/settings': {
      id: '/_authenticated/tn/admin/settings'
      path: '/tn/admin/settings'
      fullPath: '/tn/admin/settings'
      preLoaderRoute: typeof AuthenticatedTnAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tn/admin/support': {
      id: '/_authenticated/tn/admin/support'
      path: '/tn/admin/support'
      fullPath: '/tn/admin/support'
      preLoaderRoute: typeof AuthenticatedTnAdminSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCheckoutRoute: typeof AuthenticatedCheckoutRoute
  AuthenticatedCommunicationRoute: typeof AuthenticatedCommunicationRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedJathagamRoute: typeof AuthenticatedJathagamRoute
  AuthenticatedMatchesRoute: typeof AuthenticatedMatchesRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedOfficeMessagesRoute: typeof AuthenticatedOfficeMessagesRoute
  AuthenticatedRegisterRoute: typeof AuthenticatedRegisterRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedTaCommunicationRoute: typeof AuthenticatedTaCommunicationRoute
  AuthenticatedTaDashboardRoute: typeof AuthenticatedTaDashboardRoute
  AuthenticatedTaJathagamRoute: typeof AuthenticatedTaJathagamRoute
  AuthenticatedTaOfficeMessagesRoute: typeof AuthenticatedTaOfficeMessagesRoute
  AuthenticatedTaRegisterRoute: typeof AuthenticatedTaRegisterRoute
  AuthenticatedTaSupportRoute: typeof AuthenticatedTaSupportRoute
  AuthenticatedEnAdminAlertsRoute: typeof AuthenticatedEnAdminAlertsRoute
  AuthenticatedEnAdminApprovalsRoute: typeof AuthenticatedEnAdminApprovalsRoute
  AuthenticatedEnAdminCommunicationRoute: typeof AuthenticatedEnAdminCommunicationRoute
  AuthenticatedEnAdminJathagamRoute: typeof AuthenticatedEnAdminJathagamRoute
  AuthenticatedEnAdminMembersRoute: typeof AuthenticatedEnAdminMembersRoute
  AuthenticatedEnAdminMessagesRoute: typeof AuthenticatedEnAdminMessagesRoute
  AuthenticatedEnAdminPaymentsRoute: typeof AuthenticatedEnAdminPaymentsRoute
  AuthenticatedEnAdminReportsRoute: typeof AuthenticatedEnAdminReportsRoute
  AuthenticatedEnAdminSettingsRoute: typeof AuthenticatedEnAdminSettingsRoute
  AuthenticatedEnAdminSupportRoute: typeof AuthenticatedEnAdminSupportRoute
  AuthenticatedTnAdminAlertsRoute: typeof AuthenticatedTnAdminAlertsRoute
  AuthenticatedTnAdminApprovalsRoute: typeof AuthenticatedTnAdminApprovalsRoute
  AuthenticatedTnAdminCommunicationRoute: typeof AuthenticatedTnAdminCommunicationRoute
  AuthenticatedTnAdminJathagamRoute: typeof AuthenticatedTnAdminJathagamRoute
  AuthenticatedTnAdminMembersRoute: typeof AuthenticatedTnAdminMembersRoute
  AuthenticatedTnAdminMessagesRoute: typeof AuthenticatedTnAdminMessagesRoute
  AuthenticatedTnAdminPaymentsRoute: typeof AuthenticatedTnAdminPaymentsRoute
  AuthenticatedTnAdminReportsRoute: typeof AuthenticatedTnAdminReportsRoute
  AuthenticatedTnAdminSettingsRoute: typeof AuthenticatedTnAdminSettingsRoute
  AuthenticatedTnAdminSupportRoute: typeof AuthenticatedTnAdminSupportRoute
  AuthenticatedEnAdminIndexRoute: typeof AuthenticatedEnAdminIndexRoute
  AuthenticatedTnAdminIndexRoute: typeof AuthenticatedTnAdminIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCheckoutRoute: AuthenticatedCheckoutRoute,
  AuthenticatedCommunicationRoute: AuthenticatedCommunicationRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedJathagamRoute: AuthenticatedJathagamRoute,
  AuthenticatedMatchesRoute: AuthenticatedMatchesRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedOfficeMessagesRoute: AuthenticatedOfficeMessagesRoute,
  AuthenticatedRegisterRoute: AuthenticatedRegisterRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedTaCommunicationRoute: AuthenticatedTaCommunicationRoute,
  AuthenticatedTaDashboardRoute: AuthenticatedTaDashboardRoute,
  AuthenticatedTaJathagamRoute: AuthenticatedTaJathagamRoute,
  AuthenticatedTaOfficeMessagesRoute: AuthenticatedTaOfficeMessagesRoute,
  AuthenticatedTaRegisterRoute: AuthenticatedTaRegisterRoute,
  AuthenticatedTaSupportRoute: AuthenticatedTaSupportRoute,
  AuthenticatedEnAdminAlertsRoute: AuthenticatedEnAdminAlertsRoute,
  AuthenticatedEnAdminApprovalsRoute: AuthenticatedEnAdminApprovalsRoute,
  AuthenticatedEnAdminCommunicationRoute:
    AuthenticatedEnAdminCommunicationRoute,
  AuthenticatedEnAdminJathagamRoute: AuthenticatedEnAdminJathagamRoute,
  AuthenticatedEnAdminMembersRoute: AuthenticatedEnAdminMembersRoute,
  AuthenticatedEnAdminMessagesRoute: AuthenticatedEnAdminMessagesRoute,
  AuthenticatedEnAdminPaymentsRoute: AuthenticatedEnAdminPaymentsRoute,
  AuthenticatedEnAdminReportsRoute: AuthenticatedEnAdminReportsRoute,
  AuthenticatedEnAdminSettingsRoute: AuthenticatedEnAdminSettingsRoute,
  AuthenticatedEnAdminSupportRoute: AuthenticatedEnAdminSupportRoute,
  AuthenticatedTnAdminAlertsRoute: AuthenticatedTnAdminAlertsRoute,
  AuthenticatedTnAdminApprovalsRoute: AuthenticatedTnAdminApprovalsRoute,
  AuthenticatedTnAdminCommunicationRoute:
    AuthenticatedTnAdminCommunicationRoute,
  AuthenticatedTnAdminJathagamRoute: AuthenticatedTnAdminJathagamRoute,
  AuthenticatedTnAdminMembersRoute: AuthenticatedTnAdminMembersRoute,
  AuthenticatedTnAdminMessagesRoute: AuthenticatedTnAdminMessagesRoute,
  AuthenticatedTnAdminPaymentsRoute: AuthenticatedTnAdminPaymentsRoute,
  AuthenticatedTnAdminReportsRoute: AuthenticatedTnAdminReportsRoute,
  AuthenticatedTnAdminSettingsRoute: AuthenticatedTnAdminSettingsRoute,
  AuthenticatedTnAdminSupportRoute: AuthenticatedTnAdminSupportRoute,
  AuthenticatedEnAdminIndexRoute: AuthenticatedEnAdminIndexRoute,
  AuthenticatedTnAdminIndexRoute: AuthenticatedTnAdminIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PrivacyRoute: PrivacyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  TaPrivacyRoute: TaPrivacyRoute,
  TaRefundPolicyRoute: TaRefundPolicyRoute,
  TaTermsRoute: TaTermsRoute,
  TaIndexRoute: TaIndexRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
