-- Client Profile ID (SLMM-<MMYYYY><NNNN>)
-- Human-readable profile identifier, separate from profiles.id (UUID PK).
-- All UUID PK/FK relationships and RLS policies are unchanged.
-- The value is AUTHORITATIVELY generated by the database only; caller-supplied
-- values are rejected and, once assigned, the ID is immutable.

-- 1) Column — nullable because draft/unsubmitted profiles have no ID.
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS client_profile_id text;

-- 2) Format constraint: SLMM- + MM(2)YYYY(4)NNNN(4) = SLMM- + 10 digits.
ALTER TABLE public.profiles
  ADD CONSTRAINT profiles_client_profile_id_format_chk
  CHECK (client_profile_id IS NULL OR client_profile_id ~ '^SLMM-[0-9]{10}$');

-- 3) Unique partial index (allows NULL for drafts) + fast lookup by ID.
CREATE UNIQUE INDEX IF NOT EXISTS profiles_client_profile_id_uniq
  ON public.profiles (client_profile_id)
  WHERE client_profile_id IS NOT NULL;

-- 4) Per-month/year counter. period is 'MMYYYY' computed in Asia/Kolkata,
--    so the sequence resets to 0001 for every new month/year.
CREATE TABLE IF NOT EXISTS public.client_profile_id_counters (
  period     char(6) PRIMARY KEY,
  last_value integer NOT NULL DEFAULT 0
    CONSTRAINT client_profile_id_counters_last_value_chk CHECK (last_value >= 0)
);

REVOKE ALL ON TABLE public.client_profile_id_counters FROM anon, authenticated, public;

-- 5) Generator — SECURITY DEFINER with locked search_path.
--    Concurrency-safe: the ON CONFLICT ... DO UPDATE row lock serializes
--    concurrent callers on the period row, so two simultaneous submissions
--    can never receive the same number.
CREATE OR REPLACE FUNCTION public.next_client_profile_id()
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_period char(6);
  v_last   integer;
BEGIN
  v_period := to_char((now() AT TIME ZONE 'Asia/Kolkata'), 'MMYYYY');

  INSERT INTO public.client_profile_id_counters (period, last_value)
  VALUES (v_period, 1)
  ON CONFLICT (period)
    DO UPDATE SET last_value = public.client_profile_id_counters.last_value + 1
  RETURNING last_value INTO v_last;

  IF v_last > 9999 THEN
    RAISE EXCEPTION 'Client profile ID sequence exhausted for period % (max 9999 per month)', v_period
      USING ERRCODE = '22023';
  END IF;

  RETURN 'SLMM-' || v_period || lpad(v_last::text, 4, '0');
END;
$$;

REVOKE ALL ON FUNCTION public.next_client_profile_id() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.next_client_profile_id() TO service_role;

-- 6) Authoritative assignment + immutability trigger. Runs on every
--    insert/update.
--    - A non-null ID arriving on a row that has no ID yet is ALWAYS rejected
--      (RAISE 22023): the database generator inside this trigger is the only
--      writer, so callers (app, admin flows, manual SQL) can never choose or
--      pre-supply a Client Profile ID.
--    - First-time assignment happens only when the ID is still NULL and the
--      profile is (first) submitted -- the value is generated here:
--        NEW.client_profile_id IS NULL AND NEW.submitted_at IS NOT NULL
--    - Once assigned the ID is immutable: changing it or clearing it to NULL
--      raises (RAISE 55000). Because the generator is the only writer, the
--      immutability guard is authoritative for every insert/update path.
CREATE OR REPLACE FUNCTION public.assign_client_profile_id_fn()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  IF OLD.client_profile_id IS NOT NULL THEN
    IF NEW.client_profile_id IS DISTINCT FROM OLD.client_profile_id THEN
      RAISE EXCEPTION 'Client Profile ID cannot be changed once assigned'
        USING ERRCODE = '55000';
    END IF;
    RETURN NEW;
  END IF;

  IF NEW.client_profile_id IS NOT NULL THEN
    RAISE EXCEPTION
      'Client Profile ID must be assigned by the database generator; externally supplied values are not accepted'
      USING ERRCODE = '22023';
  END IF;

  IF NEW.submitted_at IS NOT NULL THEN
    NEW.client_profile_id := public.next_client_profile_id();
  END IF;

  RETURN NEW;
END;
$$;

REVOKE ALL ON FUNCTION public.assign_client_profile_id_fn() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.assign_client_profile_id_fn() TO authenticated, service_role;

DROP TRIGGER IF EXISTS profiles_assign_client_profile_id ON public.profiles;
CREATE TRIGGER profiles_assign_client_profile_id
  BEFORE INSERT OR UPDATE ON public.profiles
  FOR EACH ROW
  EXECUTE FUNCTION public.assign_client_profile_id_fn();

-- 7) Backfill existing submitted profiles (idempotent, deterministic).
--    Order: submitted_at ASC, then id ASC as the tie-breaker, preserving
--    chronological numbering within each month/year.
--    The column is only ever written as NULL here so the BEFORE INSERT OR
--    UPDATE trigger is the one that assigns each ID (submitted_at is already
--    NOT NULL). The "no externally supplied ID" rule therefore also holds
--    for the backfill.
DO $$
DECLARE
  r record;
BEGIN
  FOR r IN
    SELECT id
    FROM public.profiles
    WHERE client_profile_id IS NULL
      AND submitted_at IS NOT NULL
    ORDER BY submitted_at ASC, id ASC
  LOOP
    UPDATE public.profiles
    SET client_profile_id = NULL
    WHERE id = r.id;
  END LOOP;
END $$;